<?php

namespace Database\Seeders;

use App\Models\Tarot;
use Illuminate\Database\Seeder;

class TarotSeeder extends Seeder
{
    public function run(): void
    {
        $tarots = [
            ['number' => 1, 'name' => 'The Fool', 'image' => '01-The_Fool.jpg', 'category' => 'major', 'keywords' => 'new beginnings, innocence, spontaneity, free spirit', 'short_description' => 'The Fool represents new beginnings, having faith in the future, being inexperienced, not knowing what to expect, having beginner\'s luck, improvisation and believing in the universe.', 'long_description' => 'The Fool is a card of new beginnings, opportunity and potential. Just like the young man, you are at the outset of your journey, standing at the cliff\'s edge, and about to take your first step into the unknown. Even though you don\'t know exactly where you are going, you are being called to commit yourself and follow your heart, no matter how crazy this leap of faith might seem to you. Now is a time when you need to trust where the Universe is taking you.'],
            ['number' => 2, 'name' => 'The Magician', 'image' => '02-The_Magician.jpg', 'category' => 'major', 'keywords' => 'willpower, desire, creation, manifestation', 'short_description' => 'The Magician represents willpower, desire, resourcefulness, skill, ability, concentration, and manifestation.', 'long_description' => 'The Magician card is a reminder that you are unique and have many gifts. These skills set you apart from the crowd and can help you begin new projects or overcome adversity. When The Magician appears in your reading, it\'s a sign that you have all the tools and resources you need to manifest your desires into reality.'],
            ['number' => 3, 'name' => 'The High Priestess', 'image' => '03-The_High_Priestess.jpg', 'category' => 'major', 'keywords' => 'intuition, sacred knowledge, divine feminine, subconscious mind', 'short_description' => 'The High Priestess represents intuition, sacred knowledge, divine feminine, and the subconscious mind.', 'long_description' => 'The High Priestess sits in front of a thin veil of awareness, which is all that separates us from our deeper selves. She is the guardian of the subconscious and divine knowledge. When she appears, pay attention to your dreams and intuition, for they are guiding you toward deeper understanding.'],
            ['number' => 4, 'name' => 'The Empress', 'image' => '04-The_Empress.jpg', 'category' => 'major', 'keywords' => 'femininity, beauty, nature, nurturing, abundance', 'short_description' => 'The Empress signifies abundance, nurturing, fertility, and the beauty found in nature and life.', 'long_description' => 'The Empress is the Earth Mother of the tarot deck. She represents the fertile, life-giving Mother who reigns over the bounty of nature and the rhythms of the Earth. She is deeply connected to nature and her presence signals a time of abundance, beauty, and fertility.'],
            ['number' => 5, 'name' => 'The Emperor', 'image' => '05-The_Emperor.jpg', 'category' => 'major', 'keywords' => 'authority, structure, control, fatherhood', 'short_description' => 'The Emperor represents authority, establishment, structure, and a father figure providing stability.', 'long_description' => 'The Emperor is the father figure of the Tarot deck. He is the \'CEO\' of the Major Arcana, commanding authority and demanding structure and discipline. He represents the masculine principle, providing the rules and power to bring order to the world around him.'],
            ['number' => 6, 'name' => 'The Hierophant', 'image' => '06-The_Hierophant.jpg', 'category' => 'major', 'keywords' => 'spiritual wisdom, religious beliefs, conformity, tradition', 'short_description' => 'The Hierophant represents spiritual wisdom, religious beliefs, conformity, tradition, and institutions.', 'long_description' => 'The Hierophant is the masculine counterpart to The High Priestess. He is also known as the Pope or the Teacher. Where The High Priestess guards the esoteric, The Hierophant represents established spiritual traditions, rituals, and institutions.'],
            ['number' => 7, 'name' => 'The Lovers', 'image' => '07-The_Lovers.jpg', 'category' => 'major', 'keywords' => 'love, harmony, relationships, values alignment, choices', 'short_description' => 'The Lovers represents relationships, values alignment, and choices.', 'long_description' => 'The Lovers card represents conscious connections and meaningful relationships. This card speaks to the deep bonds between people and the choices we must make about our relationships. It speaks of harmony, mutual attraction, and the partnerships that define our lives.'],
            ['number' => 8, 'name' => 'The Chariot', 'image' => '08-The_Chariot.jpg', 'category' => 'major', 'keywords' => 'control, willpower, success, action, determination', 'short_description' => 'The Chariot represents control, willpower, victory, assertion, and determination.', 'long_description' => 'The Chariot is a card about overcoming conflicts and moving forward in a positive direction. It represents willpower, determination, and strength. When this card appears, you are being called to assert yourself and take control of the situation at hand.'],
            ['number' => 9, 'name' => 'Strength', 'image' => '09-Strength.jpg', 'category' => 'major', 'keywords' => 'strength, courage, patience, control, compassion', 'short_description' => 'Strength represents inner strength, bravery, compassion, and the power of patience and gentle force.', 'long_description' => 'The Strength card represents courage, persuasion, influence, and compassion. This card tells you that you can master a situation through the quiet mastery of your own inner strength, not through brute force, but through patience, compassion, and soft control.'],
            ['number' => 10, 'name' => 'The Hermit', 'image' => '10-The_Hermit.jpg', 'category' => 'major', 'keywords' => 'soul searching, introspection, being alone, inner guidance', 'short_description' => 'The Hermit represents soul-searching, introspection, being alone, and seeking inner guidance.', 'long_description' => 'The Hermit stands alone on the top of a mountain with a lantern in his hand. Mountains typically symbolize achievement, growth, and accomplishment. The Hermit has reached a level of enlightenment that he wishes to share, but only when the student is ready.'],
            ['number' => 11, 'name' => 'Wheel of Fortune', 'image' => '11-Wheel_of_Fortune.jpg', 'category' => 'major', 'keywords' => 'good luck, karma, life cycles, destiny, turning point', 'short_description' => 'Wheel of Fortune represents good luck, karma, life cycles, destiny, and a turning point in life.', 'long_description' => 'The Wheel of Fortune reminds us that the wheel is always turning and life is in a state of constant change. If you\'re going through a difficult time, rest assured that things will get better in time. Similarly, if things are going well, know that this cycle will change too.'],
            ['number' => 12, 'name' => 'Justice', 'image' => '12-Justice.jpg', 'category' => 'major', 'keywords' => 'justice, fairness, truth, cause and effect, law', 'short_description' => 'Justice represents justice, fairness, truth, cause and effect, and the law of karma.', 'long_description' => 'The Justice card is about reason and balance. Justice asks you to look at your situation objectively, weigh all the evidence, and make a fair and honest assessment. The truth must come out and with it the consequences of our actions.'],
            ['number' => 13, 'name' => 'The Hanged Man', 'image' => '13-The_Hangedman.jpg', 'category' => 'major', 'keywords' => 'pause, surrender, letting go, new perspectives', 'short_description' => 'The Hanged Man represents pause, surrender, letting go, and gaining new perspectives.', 'long_description' => 'The Hanged Man reflects a need to suspend action, and as a result, a period of indecision may be experienced. Decisions or actions are الأفضل that are put on hold, or الأفضل approaches will arise if you just let things be.'],
            ['number' => 14, 'name' => 'Death', 'image' => '14-Death.jpg', 'category' => 'major', 'keywords' => 'endings, change, transformation, transition', 'short_description' => 'Death represents endings, change, transformation, and transition — rarely literal death.', 'long_description' => 'The Death card is probably the most feared and misunderstood of all the major arcana. Most people take it literally; however, the card actually represents transformation, endings, and new beginnings. One door must close for another to open.'],
            ['number' => 15, 'name' => 'Temperance', 'image' => '15-Temperance.jpg', 'category' => 'major', 'keywords' => 'balance, moderation, patience, purpose', 'short_description' => 'Temperance represents balance, moderation, patience, and finding meaning through the middle path.', 'long_description' => 'Temperance is the card of moderation and balance. It suggests that you need to find the middle ground and take a moderate approach to life. Avoid extremes and find peace through patience and calm.'],
            ['number' => 16, 'name' => 'The Devil', 'image' => '16-The_Devil.jpg', 'category' => 'major', 'keywords' => 'shadow self, attachment, addiction, restriction, sexuality', 'short_description' => 'The Devil represents shadow self, attachment, addiction, restriction, and the material world.', 'long_description' => 'The Devil card represents your shadow side and the negative forces that constrain you and hold you back from being the best version of yourself. It often appears when you have been tricked into thinking you have no control over your shadow self.'],
            ['number' => 17, 'name' => 'The Tower', 'image' => '17-The_Tower.jpg', 'category' => 'major', 'keywords' => 'sudden change, upheaval, chaos, revelation, awakening', 'short_description' => 'The Tower represents sudden change, upheaval, chaos, and revelation leading to awakening.', 'long_description' => 'The Tower represents destruction, sudden change, and chaos. It is the breaking down of existing forms in order to make room for new ones. The Tower experience comes like a bolt of lightning to the structures of your life that you have built.'],
            ['number' => 18, 'name' => 'The Star', 'image' => '18-The_Star.jpg', 'category' => 'major', 'keywords' => 'hope, faith, purpose, renewal, spirituality', 'short_description' => 'The Star represents hope, faith, purpose, renewal, and spiritual connection.', 'long_description' => 'The Star brings renewed hope and faith and a sense that you are truly blessed by the Universe at this time. Courage, fulfillment, and inspiration are all within your reach. After the chaos of The Tower, The Star brings calm and tranquility.'],
            ['number' => 19, 'name' => 'The Moon', 'image' => '19-The_Moon.jpg', 'category' => 'major', 'keywords' => 'illusion, fear, anxiety, subconscious, intuition', 'short_description' => 'The Moon represents illusion, fear, anxiety, the subconscious, and the need to trust intuition.', 'long_description' => 'The Moon represents your fears and illusions and often comes out when you are projecting fear into your present and future, based on your past experiences. The Moon calls on you to release your inhibitions and let your intuition guide you.'],
            ['number' => 20, 'name' => 'The Sun', 'image' => '20-The_Sun.jpg', 'category' => 'major', 'keywords' => 'positivity, fun, warmth, success, vitality', 'short_description' => 'The Sun represents positivity, fun, warmth, success, and vitality — radiating joy.', 'long_description' => 'The Sun represents success, radiance, and abundance. The Sun gives you strength and tells you that no matter where you go or what you do, your positive and radiant energy will follow you and bring you happiness and joy.'],
            ['number' => 21, 'name' => 'Judgement', 'image' => '21-Judgement.jpg', 'category' => 'major', 'keywords' => 'judgement, rebirth, inner calling, absolution', 'short_description' => 'Judgement represents judgement, rebirth, inner calling, and absolution — answering your true calling.', 'long_description' => 'The Judgement card is calling you to rise up and embrace a higher level of consciousness for the service of your Highest Good. You are being called to reflect on your life and evaluate yourself honestly.'],
            ['number' => 22, 'name' => 'The World', 'image' => '22-The_World.jpg', 'category' => 'major', 'keywords' => 'completion, integration, accomplishment, travel', 'short_description' => 'The World represents completion, integration, accomplishment, and achieving wholeness.', 'long_description' => 'The World card in the tarot deck has a dancing figure at its center. She has successfully completed the cycle of lessons and is celebrating her achievements, having realized her vision and dreams.'],
            // Wands
            ['number' => 23, 'name' => 'Page of Wands', 'image' => '23-Page_of_Wands.jpg', 'category' => 'wands', 'keywords' => 'inspiration, ideas, discovery, limitless potential', 'short_description' => 'The Page of Wands represents inspiration, new ideas, and discovery with limitless potential.', 'long_description' => 'The Page of Wands is a messenger bringing you good news about new creative endeavors and ideas. It signals a time to explore and discover your passions.'],
            ['number' => 24, 'name' => 'Page of Swords', 'image' => '24-Page_of_Swords.jpg', 'category' => 'swords', 'keywords' => 'curiosity, restlessness, mental energy', 'short_description' => 'The Page of Swords represents new ideas, curiosity, thirst for knowledge, and mental energy.', 'long_description' => 'The Page of Swords is a card of mental energy and curiosity. You are exploring new ideas and perspectives with enthusiasm and a desire to learn.'],
            ['number' => 25, 'name' => 'Page of Pentacles', 'image' => '25-Page_of_Pentacles.jpg', 'category' => 'pentacles', 'keywords' => 'manifestation, financial opportunity, skill development', 'short_description' => 'The Page of Pentacles represents manifestation, financial opportunity, and practical skill development.', 'long_description' => 'The Page of Pentacles represents a grounded, practical approach to achieving goals. It signals new financial opportunities and the beginning of a journey toward material success.'],
            ['number' => 26, 'name' => 'Page of Cups', 'image' => '26-Page_of_Cups.jpg', 'category' => 'cups', 'keywords' => 'creative opportunities, intuitive messages, curiosity', 'short_description' => 'The Page of Cups represents creative opportunities, intuitive messages, and childlike wonder.', 'long_description' => 'The Page of Cups suggests a new emotional experience or creative opportunity is coming your way. It represents the beginning of emotional or artistic exploration.'],
            ['number' => 27, 'name' => 'Knight of Wands', 'image' => '27-Knight_of_Wands.jpg', 'category' => 'wands', 'keywords' => 'energy, passion, adventure, impulsiveness', 'short_description' => 'The Knight of Wands represents energy, passion, inspired action, and adventure.', 'long_description' => 'The Knight of Wands is full of energy and passion. He charges ahead with confidence and determination, pursuing his goals with enthusiasm and fearlessness.'],
            ['number' => 28, 'name' => 'Knight of Swords', 'image' => '28-Knight_of_Swords.jpg', 'category' => 'swords', 'keywords' => 'ambitious, action-oriented, driven to succeed', 'short_description' => 'The Knight of Swords represents ambition, action, and a driven desire to succeed quickly.', 'long_description' => 'The Knight of Swords charges forward with determination and intellectual force. He is ambitious and will not be deterred from his mission.'],
            ['number' => 29, 'name' => 'Knight of Pentacles', 'image' => '29-Knight_of_Pentacles.jpg', 'category' => 'pentacles', 'keywords' => 'hard work, productivity, routine, conservatism', 'short_description' => 'The Knight of Pentacles represents hard work, productivity, routine, and conservative approaches.', 'long_description' => 'The Knight of Pentacles is the most hardworking and dedicated of all the Knights. He is methodical, committed, and will see any task through to completion.'],
            ['number' => 30, 'name' => 'Knight of Cups', 'image' => '30-Knight_of_Cups.jpg', 'category' => 'cups', 'keywords' => 'creativity, romance, charm, imagination', 'short_description' => 'The Knight of Cups represents creativity, romance, charm, and following your heart.', 'long_description' => 'The Knight of Cups is the romantic dreamer of the Tarot. He follows his heart and lets his emotions guide him on his quest for beauty and love.'],
            ['number' => 31, 'name' => 'Queen of Wands', 'image' => '31-Queen_of_Wands.jpg', 'category' => 'wands', 'keywords' => 'courage, confidence, independence, social butterfly', 'short_description' => 'The Queen of Wands represents courage, confidence, independence, and social warmth.', 'long_description' => 'The Queen of Wands is a natural-born leader who radiates warmth and confidence. She inspires others with her passion and determination.'],
            ['number' => 32, 'name' => 'Queen of Swords', 'image' => '32-Queen_of_Swords.jpg', 'category' => 'swords', 'keywords' => 'independent, unbiased judgement, clear boundaries', 'short_description' => 'The Queen of Swords represents independent thought, unbiased judgement, and clear boundaries.', 'long_description' => 'The Queen of Swords embodies intellectual power and clear thinking. She makes decisions based on logic and clarity, unswayed by emotion.'],
            ['number' => 33, 'name' => 'Queen of Pentacles', 'image' => '33-Queen_of_Pentacles.jpg', 'category' => 'pentacles', 'keywords' => 'nurturing, practical, providing financially, working parent', 'short_description' => 'The Queen of Pentacles represents nurturing, practicality, and financial security through hard work.', 'long_description' => 'The Queen of Pentacles is the nurturing mother of the material world. She creates a warm and secure environment and manages her resources wisely.'],
            ['number' => 34, 'name' => 'Queen of Cups', 'image' => '34-Queen_of_Cups.jpg', 'category' => 'cups', 'keywords' => 'compassion, calm, comfort, emotional security', 'short_description' => 'The Queen of Cups represents compassion, calm, comfort, and deep emotional security.', 'long_description' => 'The Queen of Cups is the most emotionally nurturing figure in the Tarot. She is deeply intuitive and empathetic, offering comfort and understanding.'],
            ['number' => 35, 'name' => 'King of Wands', 'image' => '35-King_of_Wands.jpg', 'category' => 'wands', 'keywords' => 'natural-born leader, vision, entrepreneur, honour', 'short_description' => 'The King of Wands represents natural leadership, vision, entrepreneurship, and honour.', 'long_description' => 'The King of Wands is a natural-born leader who inspires those around him through his vision and determination. He takes bold action and leads by example.'],
            ['number' => 36, 'name' => 'King of Swords', 'image' => '36-King_of_Swords.jpg', 'category' => 'swords', 'keywords' => 'mental clarity, intellectual power, authority, truth', 'short_description' => 'The King of Swords represents mental clarity, intellectual power, authority, and truth.', 'long_description' => 'The King of Swords represents intellectual power, clear thinking, and authority. He uses logic and reason to make just decisions and holds truth above all.'],
            ['number' => 37, 'name' => 'King of Pentacles', 'image' => '37-King_of_Pentacles.jpg', 'category' => 'pentacles', 'keywords' => 'wealth, business, leadership, security, discipline', 'short_description' => 'The King of Pentacles represents wealth, business acumen, leadership, and financial security.', 'long_description' => 'The King of Pentacles has built his wealth and prosperity through hard work and discipline. He is a master of the material world and provides stability.'],
            ['number' => 38, 'name' => 'King of Cups', 'image' => '38-King_of_Cups.jpg', 'category' => 'cups', 'keywords' => 'emotionally balanced, compassionate, diplomatic', 'short_description' => 'The King of Cups represents emotional balance, compassion, and diplomatic wisdom.', 'long_description' => 'The King of Cups represents mastery over the emotional realm. He is compassionate, diplomatic, and maintains emotional balance even in turbulent times.'],
            // Aces
            ['number' => 39, 'name' => 'Ace of Wands', 'image' => '39-Ace_of_Wands.jpg', 'category' => 'wands', 'keywords' => 'inspiration, new opportunities, growth, potential', 'short_description' => 'The Ace of Wands represents inspiration, new opportunities, growth, and creative potential.', 'long_description' => 'The Ace of Wands is a sign that you should go for it. This card signals a new creative spark and the beginning of an exciting journey.'],
            ['number' => 40, 'name' => 'Ace of Swords', 'image' => '40-Ace_of_Swords.jpg', 'category' => 'swords', 'keywords' => 'breakthrough, clarity, sharp mind, truth', 'short_description' => 'The Ace of Swords represents breakthrough, clarity of mind, truth, and new ideas.', 'long_description' => 'The Ace of Swords signals a breakthrough in thinking and a new perspective. Mental clarity and truth cut through confusion like a sharp blade.'],
            ['number' => 41, 'name' => 'Ace of Pentacles', 'image' => '41-Ace_of_Pentacles.jpg', 'category' => 'pentacles', 'keywords' => 'new financial opportunity, manifestation, abundance', 'short_description' => 'The Ace of Pentacles represents a new financial or career opportunity and abundance.', 'long_description' => 'The Ace of Pentacles represents a new financial or material opportunity. It is the seed of prosperity and the beginning of material growth.'],
            ['number' => 42, 'name' => 'Ace of Cups', 'image' => '42-Ace_of_Cups.jpg', 'category' => 'cups', 'keywords' => 'love, new relationship, compassion, creativity', 'short_description' => 'The Ace of Cups represents new love, relationships, compassion, and emotional fulfillment.', 'long_description' => 'The Ace of Cups represents the beginning of love, compassion, and emotional fulfillment. A new relationship or deep emotional connection is on the horizon.'],
            // Twos
            ['number' => 43, 'name' => 'Two of Wands', 'image' => '43-Two_of_Wands.jpg', 'category' => 'wands', 'keywords' => 'future planning, progress, decisions, discovery', 'short_description' => 'The Two of Wands represents future planning, making progress, and important decisions ahead.', 'long_description' => 'The Two of Wands asks you to plan for the future and take steps toward your long-term goals. You are considering new territories and ventures.'],
            ['number' => 44, 'name' => 'Two of Swords', 'image' => '44-Two_of_Swords.jpg', 'category' => 'swords', 'keywords' => 'difficult choices, indecision, stalemate', 'short_description' => 'The Two of Swords represents difficult choices, indecision, and being at a crossroads.', 'long_description' => 'The Two of Swords reflects a stalemate or a difficult decision. You may be avoiding making a choice, but eventually you must face the situation head-on.'],
            ['number' => 45, 'name' => 'Two of Pentacles', 'image' => '45-Two_of_Pentacles.jpg', 'category' => 'pentacles', 'keywords' => 'multiple priorities, time management, flexibility', 'short_description' => 'The Two of Pentacles represents balancing multiple priorities and adapting to change.', 'long_description' => 'The Two of Pentacles is about balancing multiple responsibilities and staying flexible in the face of change. Juggling priorities requires adaptability.'],
            ['number' => 46, 'name' => 'Two of Cups', 'image' => '46-Two_of_Cups.jpg', 'category' => 'cups', 'keywords' => 'unified love, partnership, mutual attraction', 'short_description' => 'The Two of Cups represents unified love, partnerships, and mutual attraction.', 'long_description' => 'The Two of Cups represents a deep connection between two people. It signals partnership, mutual respect, and a harmonious relationship.'],
            // Threes
            ['number' => 47, 'name' => 'Three of Wands', 'image' => '47-Three_of_Wands.jpg', 'category' => 'wands', 'keywords' => 'progress, expansion, foresight, overseas opportunities', 'short_description' => 'The Three of Wands represents progress, expansion, and looking ahead to new opportunities.', 'long_description' => 'The Three of Wands shows your plans are taking shape and you are looking ahead to future growth. Expansion and broadening horizons await.'],
            ['number' => 48, 'name' => 'Three of Swords', 'image' => '48-Three_of_Swords.jpg', 'category' => 'swords', 'keywords' => 'heartbreak, emotional pain, sorrow, grief', 'short_description' => 'The Three of Swords represents heartbreak, emotional pain, and sorrow that leads to growth.', 'long_description' => 'The Three of Swords depicts heartbreak and emotional pain. While this is a difficult card, it reminds us that through pain comes growth and healing.'],
            ['number' => 49, 'name' => 'Three of Pentacles', 'image' => '49-Three_of_Pentacles.jpg', 'category' => 'pentacles', 'keywords' => 'teamwork, collaboration, learning, implementation', 'short_description' => 'The Three of Pentacles represents teamwork, collaboration, and skilled craftsmanship.', 'long_description' => 'The Three of Pentacles celebrates teamwork and collaboration. Your skills are being recognized and you are working well with others to achieve a common goal.'],
            ['number' => 50, 'name' => 'Three of Cups', 'image' => '50-Three_of_Cups.jpg', 'category' => 'cups', 'keywords' => 'celebration, friendship, creativity, collaborations', 'short_description' => 'The Three of Cups represents celebration, friendship, and joyful collaborations.', 'long_description' => 'The Three of Cups is a card of celebration, friendship, and community. It signals a time of joy and coming together with those you love.'],
            // Fours
            ['number' => 51, 'name' => 'Four of Wands', 'image' => '51-Four_of_Wands.jpg', 'category' => 'wands', 'keywords' => 'celebration, joy, harmony, relaxation, homecoming', 'short_description' => 'The Four of Wands represents celebration, harmony, homecoming, and joyful community.', 'long_description' => 'The Four of Wands is a time of celebration and homecoming. You have reached a significant milestone and it is time to celebrate your achievements.'],
            ['number' => 52, 'name' => 'Four of Swords', 'image' => '52-Four_of_Swords.jpg', 'category' => 'swords', 'keywords' => 'rest, relaxation, meditation, contemplation, recuperation', 'short_description' => 'The Four of Swords represents rest, meditation, contemplation, and the need for recuperation.', 'long_description' => 'The Four of Swords calls for a period of rest and recuperation. Take time to recharge, meditate, and reflect before moving forward.'],
            ['number' => 53, 'name' => 'Four of Pentacles', 'image' => '53-Four_of_Pentacles.jpg', 'category' => 'pentacles', 'keywords' => 'saving money, security, conservatism, scarcity', 'short_description' => 'The Four of Pentacles represents saving, security, control, and sometimes scarcity mindset.', 'long_description' => 'The Four of Pentacles is about holding on to what you have and maintaining financial security. Be careful not to let this turn into greed or stinginess.'],
            ['number' => 54, 'name' => 'Four of Cups', 'image' => '54-Four_of_Cups.jpg', 'category' => 'cups', 'keywords' => 'meditation, contemplation, apathy, reevaluation', 'short_description' => 'The Four of Cups represents contemplation, apathy, and the need to look at life from a new angle.', 'long_description' => 'The Four of Cups shows someone so caught up in contemplation that they miss new opportunities being presented. It is a call to open your eyes.'],
            // Fives
            ['number' => 55, 'name' => 'Five of Wands', 'image' => '55-Five_of_Wands.jpg', 'category' => 'wands', 'keywords' => 'disagreements, competition, tension, conflict', 'short_description' => 'The Five of Wands represents disagreements, competition, tension, and creative differences.', 'long_description' => 'The Five of Wands represents competition and conflict. People are clashing and there is disagreement, but this tension can be constructive if channeled well.'],
            ['number' => 56, 'name' => 'Five of Swords', 'image' => '56-Five_of_Swords.jpg', 'category' => 'swords', 'keywords' => 'conflict, disagreements, competition, defeat, winning at all costs', 'short_description' => 'The Five of Swords represents conflict, defeat, and the hollow feeling of winning at all costs.', 'long_description' => 'The Five of Swords is a card warning of conflict. Even if you win, the cost may be too high. Consider whether the battle is worth fighting.'],
            ['number' => 57, 'name' => 'Five of Pentacles', 'image' => '57-Five_of_Pentacles.jpg', 'category' => 'pentacles', 'keywords' => 'financial loss, poverty, lack mindset, isolation', 'short_description' => 'The Five of Pentacles represents financial hardship, feeling left out, and needing to seek help.', 'long_description' => 'The Five of Pentacles signals financial hardship and feeling left out in the cold. Help is available if you are willing to seek it.'],
            ['number' => 58, 'name' => 'Five of Cups', 'image' => '58-Five_of_Cups.jpg', 'category' => 'cups', 'keywords' => 'regret, failure, disappointment, pessimism', 'short_description' => 'The Five of Cups represents regret, failure, and the need to find the silver lining.', 'long_description' => 'The Five of Cups focuses on loss and what has been spilled. But behind you, two cups still stand. This card reminds you to see what remains, not only what was lost.'],
            // Sixes
            ['number' => 59, 'name' => 'Six of Wands', 'image' => '59-Six_of_Wands.jpg', 'category' => 'wands', 'keywords' => 'success, public recognition, progress, self-confidence', 'short_description' => 'The Six of Wands represents success, public recognition, and triumphant progress.', 'long_description' => 'The Six of Wands is a card of victory and public acknowledgment. Your hard work has paid off and others are celebrating your achievements.'],
            ['number' => 60, 'name' => 'Six of Swords', 'image' => '60-Six_of_Swords.jpg', 'category' => 'swords', 'keywords' => 'transition, change, rite of passage, releasing baggage', 'short_description' => 'The Six of Swords represents transition, moving on, and leaving difficulties behind.', 'long_description' => 'The Six of Swords signals a period of transition. You are moving away from turbulent waters toward calmer shores, leaving behind what no longer serves you.'],
            ['number' => 61, 'name' => 'Six of Pentacles', 'image' => '61-Six_of_Pentacles.jpg', 'category' => 'pentacles', 'keywords' => 'giving, receiving, sharing wealth, generosity', 'short_description' => 'The Six of Pentacles represents giving, receiving, generosity, and sharing prosperity.', 'long_description' => 'The Six of Pentacles is about the flow of resources. Whether you are giving or receiving, there is a balance of generosity and gratitude.'],
            ['number' => 62, 'name' => 'Six of Cups', 'image' => '62-Six_of_Cups.jpg', 'category' => 'cups', 'keywords' => 'revisiting the past, childhood memories, innocence, joy', 'short_description' => 'The Six of Cups represents nostalgia, childhood memories, and the joy of simple pleasures.', 'long_description' => 'The Six of Cups is a card of nostalgia and happy memories. It may signal a reunion or a return to a simpler, more innocent time.'],
            // Sevens
            ['number' => 63, 'name' => 'Seven of Wands', 'image' => '63-Seven_of_Wands.jpg', 'category' => 'wands', 'keywords' => 'challenge, competition, protection, perseverance', 'short_description' => 'The Seven of Wands represents standing your ground, challenge, and perseverance.', 'long_description' => 'The Seven of Wands shows you defending your position against opposition. You have worked hard and now must stand firm in your beliefs and achievements.'],
            ['number' => 64, 'name' => 'Seven of Swords', 'image' => '64-Seven_of_Swords.jpg', 'category' => 'swords', 'keywords' => 'betrayal, deception, getting away with something, stealth', 'short_description' => 'The Seven of Swords represents deception, strategy, and acting with stealth.', 'long_description' => 'The Seven of Swords suggests that someone may be acting deceptively or that a strategic, stealthy approach is needed. Be cautious of trickery.'],
            ['number' => 65, 'name' => 'Seven of Pentacles', 'image' => '65-Seven_of_Pentacles.jpg', 'category' => 'pentacles', 'keywords' => 'long-term view, sustainable results, perseverance, investment', 'short_description' => 'The Seven of Pentacles represents patience, long-term investment, and waiting for results.', 'long_description' => 'The Seven of Pentacles asks you to take a long-term view. Your investments and efforts are growing, even if you cannot yet see the results.'],
            ['number' => 66, 'name' => 'Seven of Cups', 'image' => '66-Seven_of_Cups.jpg', 'category' => 'cups', 'keywords' => 'opportunities, choices, wishful thinking, illusion', 'short_description' => 'The Seven of Cups represents many choices, wishful thinking, and the need for discernment.', 'long_description' => 'The Seven of Cups presents many options and possibilities, but not all may be what they seem. Discernment and focus are needed to choose wisely.'],
            // Eights
            ['number' => 67, 'name' => 'Eight of Wands', 'image' => '67-Eight_of_Wands.jpg', 'category' => 'wands', 'keywords' => 'speed, action, air travel, movement, swift change', 'short_description' => 'The Eight of Wands represents speed, rapid action, movement, and things coming together quickly.', 'long_description' => 'The Eight of Wands signals rapid movement and swift progress. Things are happening fast and momentum is on your side.'],
            ['number' => 68, 'name' => 'Eight of Swords', 'image' => '68-Eight_of_Swords.jpg', 'category' => 'swords', 'keywords' => 'imprisonment, entrapment, self-victimization, limiting beliefs', 'short_description' => 'The Eight of Swords represents feeling trapped, restricted, and held back by limiting beliefs.', 'long_description' => 'The Eight of Swords shows someone who has been blindfolded and bound. The restrictions are self-imposed — freedom is within reach if you change your perspective.'],
            ['number' => 69, 'name' => 'Eight of Pentacles', 'image' => '69-Eight_of_Pentacles.jpg', 'category' => 'pentacles', 'keywords' => 'apprenticeship, repetitive tasks, mastery, skill development', 'short_description' => 'The Eight of Pentacles represents dedication, mastery, and focused skill development.', 'long_description' => 'The Eight of Pentacles is the card of the apprentice. Through dedicated practice and repetition, you are mastering your craft.'],
            ['number' => 70, 'name' => 'Eight of Cups', 'image' => '70-Eight_of_Cups.jpg', 'category' => 'cups', 'keywords' => 'disappointment, abandonment, withdrawal, escapism', 'short_description' => 'The Eight of Cups represents walking away, seeking deeper meaning, and leaving behind what no longer fulfills.', 'long_description' => 'The Eight of Cups shows a figure walking away from a stack of cups. Despite having much, something is missing, and it is time to search for deeper meaning.'],
            // Nines
            ['number' => 71, 'name' => 'Nine of Wands', 'image' => '71-Nine_of_Wands.jpg', 'category' => 'wands', 'keywords' => 'resilience, courage, persistence, test of faith', 'short_description' => 'The Nine of Wands represents resilience, courage, and persistence through challenges.', 'long_description' => 'The Nine of Wands shows someone who has been through battles but still stands strong. Your resilience will carry you through this final challenge.'],
            ['number' => 72, 'name' => 'Nine of Swords', 'image' => '72-Nine_of_Swords.jpg', 'category' => 'swords', 'keywords' => 'anxiety, worry, fear, depression, nightmares', 'short_description' => 'The Nine of Swords represents anxiety, worry, fear, and sleepless nights.', 'long_description' => 'The Nine of Swords depicts anxiety and worry that keeps you up at night. Much of this fear may be self-created. Reach out for support and perspective.'],
            ['number' => 73, 'name' => 'Nine of Cups', 'image' => '73-Nine_of_Cups.jpg', 'category' => 'cups', 'keywords' => 'contentment, satisfaction, gratitude, wish come true', 'short_description' => 'The Nine of Cups represents contentment, satisfaction, and wishes being fulfilled.', 'long_description' => 'The Nine of Cups is known as the "wish card." It signals that your wishes and desires are coming true. Enjoy this time of satisfaction and abundance.'],
            ['number' => 74, 'name' => 'Nine of Pentacles', 'image' => '74-Nine_of_Pentacles.jpg', 'category' => 'pentacles', 'keywords' => 'abundance, luxury, self-sufficiency, financial independence', 'short_description' => 'The Nine of Pentacles represents abundance, luxury, self-sufficiency, and financial independence.', 'long_description' => 'The Nine of Pentacles celebrates self-sufficiency and the rewards of hard work. You have created a life of abundance and luxury through your own efforts.'],
            // Tens
            ['number' => 75, 'name' => 'Ten of Wands', 'image' => '75-Ten_of_Wands.jpg', 'category' => 'wands', 'keywords' => 'burden, extra responsibility, hard work, completion', 'short_description' => 'The Ten of Wands represents burden, extra responsibility, and being weighed down by hard work.', 'long_description' => 'The Ten of Wands shows someone carrying a heavy burden. While you have taken on much, the end is in sight. Consider delegating some responsibilities.'],
            ['number' => 76, 'name' => 'Ten of Swords', 'image' => '76-Ten_of_Swords.jpg', 'category' => 'swords', 'keywords' => 'painful endings, deep wounds, betrayal, loss, crisis', 'short_description' => 'The Ten of Swords represents painful endings, loss, and the need for a fresh start.', 'long_description' => 'The Ten of Swords represents a painful ending. While this is the lowest point, the only way from here is up. A new dawn awaits.'],
            ['number' => 77, 'name' => 'Ten of Pentacles', 'image' => '77-Ten_of_Pentacles.jpg', 'category' => 'pentacles', 'keywords' => 'wealth, financial security, family, long-term success', 'short_description' => 'The Ten of Pentacles represents wealth, family, long-term security, and legacy.', 'long_description' => 'The Ten of Pentacles represents the culmination of financial and material success. It speaks to wealth, family heritage, and long-term stability.'],
            ['number' => 78, 'name' => 'Ten of Cups', 'image' => '78-Ten_of_Cups.jpg', 'category' => 'cups', 'keywords' => 'divine love, blissful relationships, harmony, alignment', 'short_description' => 'The Ten of Cups represents divine love, blissful relationships, harmony, and emotional fulfillment.', 'long_description' => 'The Ten of Cups is the ultimate card of emotional fulfillment and familial bliss. Your relationships are harmonious and your heart is full.'],
        ];

        foreach ($tarots as $tarot) {
            Tarot::create($tarot);
        }
    }
}
